### ISSUE TITLE
publish for Scala 2.13?

### ISSUE THREAD

**Issue by SethTisue** [scalatest/scalatestplus-scalacheck#10]

**Comment by kevinwright** [comment]
Please please please... There's a lot of downstream projects waiting on this

**Comment by xuwei-k** [comment]
https://repo1.maven.org/maven2/org/scalatestplus/scalatestplus-scalacheck_sjs0.6_2.13/
https://repo1.maven.org/maven2/org/scalatestplus/scalatestplus-scalacheck_2.13/

🎉

**Comment by SethTisue** [comment]
this ticket can be closed, I think?

**Comment by cheeseng** [comment]
Thanks @SethTisue , closing now.
