### ISSUE TITLE
Release for ScalaTest 3.1.0

### ISSUE THREAD

**Issue by slandelle** [scalatest/scalatestplus-scalacheck#17]
Hi there,

ScalaTest 3.1.0 release note states:

> From now on these will be released as a separate, optional module to allow ScalaTest and its ScalaCheck integration library to evolve more independently.

Please correct me if I'm wrong, but I can't find any information regarding the correct version that should be used with scalatest 3.1.0 and it looks from the commit log here that this project hasn't released a compatible version. Same question for scalatestplus-mockito.

Thanks in advance.

**Comment by jhnsmth** [comment]
I looks like it was [released](https://github.com/scalatest/scalatestplus-scalacheck/releases/tag/release-3.1.0.0-for-scalacheck-1.14) but no [artifacts](https://mvnrepository.com/artifact/org.scalatestplus/scalatestplus-scalacheck) were published

**Comment by slandelle** [comment]
@jhnsmth mvnrepository is a third party index and it always lags behind.
The official correct index is search.maven.org.

Thanks for releasing!

**Comment by slandelle** [comment]
https://search.maven.org/artifact/org.scalatestplus/scalacheck-1-14_2.12
