### ISSUE TITLE
Artifact for 3.1.0.0 seems missing?

### ISSUE THREAD

**Issue by gvolpe** [scalatest/scalatestplus-scalacheck#21]
Hi,

I'm trying to update a project and can't seem to find the artifact for the [latest tagged version 3.1.0.0](https://github.com/scalatest/scalatestplus-scalacheck/releases/tag/release-3.1.0.0-for-scalacheck-1.14).

The last one is `3.2.0.1-M1`: https://search.maven.org/search?q=org.scalatestplus.scalacheck-1.14

Is it published somewhere else?

**Comment by cheeseng** [comment]
@gvolpe It is listed here: 

https://mvnrepository.com/artifact/org.scalatestplus/scalacheck-1-14

**Comment by gvolpe** [comment]
My mistake. I was searching for `scalacheck-1.14` instead of `scalacheck-1-14` :man_facepalming:
