### ISSUE TITLE
Please publish the latest releases

### ISSUE THREAD

**Issue by markehammons** [scalatest/scalatestplus-scalacheck#28]
The latest release available on maven repository is 3.1.0.0-RC2

**Comment by AlterEgo7** [comment]
@markehammons Just follow the example from #19 .

**Comment by abdolence** [comment]
I don't know why this isn't in the readme already, but it is available if you use this:
```
libraryDependencies += "org.scalatestplus" %% "scalacheck-1-14" % "3.1.1.1" % "test"
```

**Comment by markehammons** [comment]
I see. Thanks for the information.
