### ISSUE TITLE
Dotty release

### ISSUE THREAD

**Issue by LukaJCB** [scalatest/scalatestplus-scalacheck#29]
I see travis opened up #24 for dotty support, any chance we can can merge that and get a release?

**Comment by vigoo** [comment]
It compiles fine with 3.0.0-M3, would it be possible to have a published artifact please (at least snapshot)?

**Comment by kubukoz** [comment]
Looks like that's released. Now we just need 3.0.0 final :)

**Comment by kubukoz** [comment]
no wait, it's there: https://repo1.maven.org/maven2/org/scalatestplus/scalacheck-1-15_3/3.2.9.0/

**Comment by bvenners** [comment]
Yes, all 3.2.9 artifacts are released and should show up on Maven Central soon if not already.
