### ISSUE TITLE
missing release for `3.1.2.0`

### ISSUE THREAD

**Issue by yanns** [scalatest/scalatestplus-scalacheck#30]
missing [release](https://github.com/scalatest/scalatestplus-scalacheck/releases) for `3.1.2.0`

**Comment by cheeseng** [comment]
@yanns It is released as scalacheck-1-14 here: 

https://mvnrepository.com/artifact/org.scalatestplus/scalacheck-1-14

**Comment by yanns** [comment]
@cheeseng Yes, thx I saw that.
That's why I came here to check for the new release.
But I cannot find any git tag for it.
Forgot to push the git tag?

**Comment by cheeseng** [comment]
@yanns  Ah you're right, I forgot to create release here.  Fyi, afaik do not have any changes (bug fix, enhancement etc.) except for building for different version of scalatest released.  I'll start to create back the releases (and its tags).  Sorry for the confusion caused.

**Comment by cheeseng** [comment]
@yanns Finally created here: 

https://github.com/scalatest/scalatestplus-scalacheck/releases/tag/release-3.1.2.0-for-scalacheck-1.14

Thanks again for you kind reminder.

**Comment by yanns** [comment]
cool, thx a lot!
For info, I use https://github.com/apps/release-drafter on some projects I manage to automate part of the release notes.

**Comment by cheeseng** [comment]
@yanns release-drafter looks good, thanks for introducing it to us!
