### ISSUE TITLE
Request for Scala Native 0.5.x support

### ISSUE THREAD

**Issue by ekrich** [scalatest/scalatestplus-scalacheck#65]
Thanks! Waiting on the following:

- [ ] https://github.com/scalatest/scalatest/pull/2322
- [X] https://github.com/typelevel/scalacheck/releases/tag/v1.18.0

**Comment by cheeseng** [comment]
@ekrich Fyi I'll stage it today.

**Comment by cheeseng** [comment]
I submitted the following PR: 

https://github.com/scalatest/scalatestplus-scalacheck/pull/66

and staged the artifacts, @bvenners shall have the pleasure to release it.

Cheers.

**Comment by ekrich** [comment]
It looks like you only published `1-18` for Scala Native and I have a cross project with JS and JVM too - could those also be published so they can all match the same artifact?

**Comment by cheeseng** [comment]
@ekrich I have published also for JS and JVM too, can you check again to see if they work for you?
